server:
  port: 9001

spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: autenticaciondb
    schema: public
    username: postgres
    password: 1234
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    co.com.pragma: TRACE

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "fa9e14cbf255996c837711a02c590f242d4626481019d5ed94a432922523e4a5"
  expiration: 3600000